name: CI/CD Pipeline

on:
  push:
    branches:
      - withcicd
  pull_request:
    branches:
      - withcicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        env:
          IMAGE_TAG: latest
        run:  |
              docker build -t ${{ secrets.ECR_REGISTRY_URL }}:$IMAGE_TAG .
              echo "build complete"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Image Push  
        run:  docker push ${{ secrets.ECR_REGISTRY_URL }}:$IMAGE_TAG