name: CI/CD Pipeline


on:
  push:
    branches:
      - withcicd
  pull_request:
    branches:
      - withcicd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        env:
          IMAGE_TAG: latest
        run:  |
              docker build -t ${{ secrets.ECR_REGISTRY_URL }}:$IMAGE_TAG .
              echo "build complete"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Image Push  
        run:  docker push ${{ secrets.ECR_REGISTRY_URL }}:$IMAGE_TAG